cask_args appdir: '/Applications'

brew 'openssl'
brew 'rbenv'
brew 'ruby-build'
brew 'tmux'
brew 'mas'
brew 'vim'

cask 'google-chrome'
cask 'google-japanese-ime'
cask 'karabiner'
cask 'dropbox'
cask 'kindle'
cask 'iterm2'
cask 'skitch'
cask 'unity'
cask 'blender'

# App Store applications
# mas signin
mas 'Minutes', id: 406827163
mas 'Slack', id: 803453959
mas 'Wunderlist', id: 410628904

